import type {Metadata} from "next";
import Navbar from "@/components/core/navbar";
import {Toaster} from "@/components/ui/sonner";
import {Footer} from "@/components/core/footer/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Navbar/>
            <Toaster/>
            <div className="items-center justify-items-center min-h-screen font-[family-name:var(--font-geist-sans)]">
                {children}
            </div>
            <Footer/>
        </>
    );
}
