import type {Metadata} from "next";
import {Geist, Geist_Mono, Roboto, Roboto_Mono,  Roboto_Serif} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-roboto-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-roboto-mono",
    subsets: ["latin"],
});

const roboto = Roboto({
    variable: "--font-roboto",
    subsets: ["latin"],
    weight: ["400", "700"], // Optional: You can specify weights
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} subpixel-antialiased bg-gradient-to-r from-indigo-100 via-purple-100 to-pink-100 text-xl font-medium`}
        >{children}
        </body>
        </html>
    );
}
